-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:664b43c6d9fcf02235d58af09d8359cb$
-- 

return {
	texture = 'asset/image/asset-button.png',
	frames = {
			{
				name = "button_basic.png",
				spriteColorRect = { x = 21, y = 20, width = 267, height = 269 },
				uvRect = { u0 = 0.00195312, v0 = 0.00195312, u1 = 0.262695, v1 = 0.264648 },
				spriteSourceSize = { width = 307, height = 307 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "button_lock-hover.png",
				spriteColorRect = { x = 21, y = 20, width = 267, height = 269 },
				uvRect = { u0 = 0.00195312, v0 = 0.53125, u1 = 0.262695, v1 = 0.793945 },
				spriteSourceSize = { width = 307, height = 307 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "button_lock.png",
				spriteColorRect = { x = 21, y = 20, width = 267, height = 269 },
				uvRect = { u0 = 0.00195312, v0 = 0.266602, u1 = 0.262695, v1 = 0.529297 },
				spriteSourceSize = { width = 307, height = 307 },
				spriteTrimmed = true,
				textureRotated = false
			},
			{
				name = "button_play-hover.png",
				spriteColorRect = { x = 21, y = 20, width = 267, height = 269 },
				uvRect = { u0 = 0.529297, v0 = 0.00195312, u1 = 0.791992, v1 = 0.262695 },
				spriteSourceSize = { width = 307, height = 307 },
				spriteTrimmed = true,
				textureRotated = true
			},
			{
				name = "button_play.png",
				spriteColorRect = { x = 21, y = 20, width = 267, height = 269 },
				uvRect = { u0 = 0.264648, v0 = 0.00195312, u1 = 0.527344, v1 = 0.262695 },
				spriteSourceSize = { width = 307, height = 307 },
				spriteTrimmed = true,
				textureRotated = true
			},
		}
	}

