-- This file is for use with Moai SDK
-- 
-- This file is automatically generated with TexturePacker (http://texturepacker.com). Do not edit
-- $TexturePacker:SmartUpdate:6837154b3d8cfc9a674bc13ecdc5d7ec$
-- 

return {
	texture = 'asset/image/button-level.png',
	frames = {
			{
				name = "btn-off.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 60 },
				uvRect = { u0 = 0, v0 = 0, u1 = 1, v1 = 0.5 },
				spriteSourceSize = { width = 60, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
			{
				name = "btn-on.png",
				spriteColorRect = { x = 0, y = 0, width = 60, height = 60 },
				uvRect = { u0 = 0, v0 = 0.5, u1 = 1, v1 = 1 },
				spriteSourceSize = { width = 60, height = 60 },
				spriteTrimmed = false,
				textureRotated = false
			},
		}
	}

